### ISSUE TITLE
The server crashes after installation mysql_mm.so

### ISSUE THREAD

**Issue by ezekutor** [Salvatore-Als/cs2-rank#23]
https://github.com/Salvatore-Als/cs2-rank/releases/tag/cs2-dependencies

**Comment by Salvatore-Als** [comment]
Please, try the b2.0 version, It works on Linux as well as on Windows.

You must be careful to install the mysql_mm plugin and connect your mysql server, if the mysql_mm plugin does not exist or the database does not connect the plugin unloads and crashes the server (I suspect a problem with metamod, I still have to see this point).

Don't hesitate to use this plugin (only on Linux) https://github.com/komashchenko/AcceleratorLocal in order to have crashdumps :)

**Comment by ezekutor** [comment]
I compiled it myself, everything worked for me. But for some reason the bots are standing and not moving )

**Comment by ezekutor** [comment]
`[STARTUP] {2.308} server module init ok
CS2 Rank - Missing MYSQL plugin
CHostStateMgr::QueueNewRequest( Idle (console), 1 )
Source2Init OK
HostStateRequest::Start(HSR_IDLE):  loop(console) id(1) addons() desc(Idle (console))
SwitchToLoop console requested:  id [1] addons []
Host activate: Idle (console)
Setting mapgroup to 'mg_de_mirage'
Loading map "de_mirage"
CHostStateMgr::QueueNewRequest( Loading (de_mirage), 2 )
free(): invalid size
Aborted (core dumped)`

**Comment by Salvatore-Als** [comment]
For the bot it's my fault, I block them for my test, i'm currently working on feature, the commit will contain the bot fix.

For your issue, as you can see "Missing MYSQL plugin", mean that mysql_mm is missing from your server.

**Comment by ezekutor** [comment]
This happens when I install the mysql_mm plugin compiled by you, when I install my own, everything works, I will attach my own
[package.zip](https://github.com/Salvatore-Als/cs2-rank/files/13431218/package.zip)

**Comment by Salvatore-Als** [comment]
Thx for the report, I will fix the package after finishing the beta update, there is a fucking crash trying to understand

**Comment by ezekutor** [comment]
I'll test it tomorrow and let you know if something goes wrong.

**Comment by asdfxD** [comment]
my game is in english and i get i guess "french" language in chat? how can i fix this?

**Comment by ezekutor** [comment]
> I have release a new version, bot should not be blocked, moreover it included many fix :)

I checked everything works well. If there is a desire and strength , you can include ranking by weapons , by jump kills, through smoke, by shooting, with a knife and give out a certain number of points for this

**Comment by Salvatore-Als** [comment]
This is a beta to be sure that i'ts working, I will add more stats when the beta will be stable :D

Thx for the feedback.

**Comment by Salvatore-Als** [comment]
> my game is in english and i get i guess "french" language in chat? how can i fix this?

Tu devrais lire la documentation.
