### ISSUE TITLE
Copying the same player (web site module)

### ISSUE THREAD

**Issue by emrahkaraduman** [Salvatore-Als/cs2-rank#28]
It duplicates the same player in the ranking section, but when I reload the page, the issue partially resolves. I think it could be a bug I am using the latest version.

![image](https://github.com/Salvatore-Als/cs2-rank/assets/33588333/acc9bb81-f586-4e09-bc8f-80b1927c90fc)
![image](https://github.com/Salvatore-Als/cs2-rank/assets/33588333/aadfb4de-dcbe-45c7-a110-0ab401615d9e)

**Comment by Salvatore-Als** [comment]
Can you confirm on your database that the player have the same authidId, reference and map please ?
